<a href="https://colab.research.google.com/github/msy-bilecik/ist204_2025/blob/main/ist204_2025_12h.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>


https://web.itu.edu.tr/iguzel/files/Python_Cheat_Sheets.pdf

In [ ]:
import numpy as np

In [ ]:
a = np.array([1,2,3])
b = np.array([(1.5,2,3), (4,5,6)], dtype = float)
c = np.array([[(1.5,2,3), (4,5,6)], [(3,2,1), (4,5,6)]],dtype = float)
print(a)
print(b)
print(c)

[1 2 3]
[[1.5 2.  3. ]
 [4.  5.  6. ]]
[[[1.5 2.  3. ]
  [4.  5.  6. ]]

 [[3.  2.  1. ]
  [4.  5.  6. ]]]


In [ ]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
np.ones((2,3,4),dtype=np.int16)

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int16)

In [ ]:
d = np.arange(10,40,5)
print(d)

[10 15 20 25 30 35]


In [ ]:
np.linspace(0,2,9) # 0 ile 2 arasında 9 parçalı bir dizi yap

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  ])

In [ ]:
e = np.full((2,2),7)
print(e)

[[7 7]
 [7 7]]


In [ ]:
f = np.eye(2)
print(f)

[[1. 0.]
 [0. 1.]]


In [ ]:
np.random.random((2,2))

array([[0.61126739, 0.87401936],
       [0.99663169, 0.08921958]])

In [ ]:
np.empty((3,2))

array([[1.5, 2. ],
       [3. , 4. ],
       [5. , 6. ]])

In [ ]:
np.save('my_array', a,b,c)


In [ ]:
a,b,c=np.load('my_array.npy')
print(a)

1


In [ ]:
print(c)
print(c.shape)
print(len(c))
print(c.ndim)
print(c.size)

[[[1.5 2.  3. ]
  [4.  5.  6. ]]

 [[3.  2.  1. ]
  [4.  5.  6. ]]]
(2, 2, 3)
2
3
12


In [ ]:
np.info(np.ndarray.dtype)

Data-type of the array's elements.

.. warning::

    Setting ``arr.dtype`` is discouraged and may be deprecated in the
    future.  Setting will replace the ``dtype`` without modifying the
    memory (see also `ndarray.view` and `ndarray.astype`).

Parameters
----------
None

Returns
-------
d : numpy dtype object

See Also
--------
ndarray.astype : Cast the values contained in the array to a new data-type.
ndarray.view : Create a view of the same data but a different data-type.
numpy.dtype

Examples
--------
>>> x
array([[0, 1],
       [2, 3]])
>>> x.dtype
dtype('int32')
>>> type(x.dtype)
<type 'numpy.dtype'>


In [ ]:
print(b)
print(a)
print(b+a)
print(np.add(b,a))


[[1.5 2.  3. ]
 [4.  5.  6. ]]
[1 2 3]
[[2.5 4.  6. ]
 [5.  7.  9. ]]
[[2.5 4.  6. ]
 [5.  7.  9. ]]


In [ ]:
a==b

array([[False,  True,  True],
       [False, False, False]])

In [ ]:
a=np.array([13,3,2])
print(a==b)

[[False False False]
 [False False False]]


In [ ]:
print(b)
print(b.max(axis=1)) # **

[[1.5 2.  3. ]
 [4.  5.  6. ]]
[3. 6.]


In [ ]:
a.mean()

np.float64(6.0)

In [ ]:
np.std(b)

np.float64(1.5920810978785667)